In [3]:
#Print
print('kelas bahasa')

kelas bahasa


In [4]:
#Variabel
a = 34;
b = 32
a, b

(34, 32)

In [6]:
#List
a = [1, 2, 4, 5, 6]
a
a[0]
a[1]

2

In [8]:
#tambah data
a.append(3)
a

[1, 2, 4, 5, 6, 3, 3]

In [9]:
a.sort()

In [10]:
a

[1, 2, 3, 3, 4, 5, 6]

In [11]:
a[1:6:2]

[2, 3, 5]

In [12]:
a[::-1]

[6, 5, 4, 3, 3, 2, 1]

In [16]:
#dictionary
Jenis = {
    "hewan": "kuda",
    "buah": "mangga",
    "burung": "kenari"
}

Jenis.keys()
Jenis.values()

dict_values(['kuda', 'mangga', 'kenari'])

In [17]:
Jenis['burung']

'kenari'

In [18]:
#Nulis fungsi
def hasilBagi(a, b):
    return a % b

hasilBagi(10000, 3)

1

In [19]:
def inputData(a):
    return a
inputData('data berhasil di buat')

'data berhasil di buat'

In [24]:
#condition
angga = 90

if angga < 70:
    print('Remidi bro')
elif angga > 70 & angga < 80:
    print('oke juga nilai lu')
elif angga > 80:
    print('masuk pak eko')
else:
    print('data tidak ditemukan')

oke juga nilai lu


In [25]:
#iterasi
bilangan = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for angka in bilangan:
    print(angka)

1
2
3
4
5
6
7
8
9


In [32]:
for angka in (70, 80, 90, 75, 85, 95):
    print(angka)

70
80
90
75
85
95


In [35]:
for angka in range(2, 7):
    print(angka)

2
3
4
5
6


In [38]:
for kucing in Jenis:
    print(kucing) 

hewan
buah
burung


In [43]:
listSiswa = ["sisil", "Ridwan", "putri", "Rafly", "Lina", "Gilang"]
for siswa in listSiswa:
    print("nama dia " + siswa)

nama dia sisil
nama dia Ridwan
nama dia putri
nama dia Rafly
nama dia Lina
nama dia Gilang


In [44]:
list = [ ]
for nilai in list:
    return nilai
nilai(21, 22)

SyntaxError: 'return' outside function (<ipython-input-44-0d09de1c2e07>, line 3)

In [47]:
for angka in range(10, 20):
    if angka > 15:
        print('angka sampai 15 saja')
    else:
        print(angka)

10
11
12
13
14
15
angka sampai 15 saja
angka sampai 15 saja
angka sampai 15 saja
angka sampai 15 saja


In [50]:
for angkaGanjil in range(1, 20):
    if angkaGanjil > 15:
        print('angka melampaui batas')
    else:
        print(angkaGanjil)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
angka melampaui batas
angka melampaui batas
angka melampaui batas
angka melampaui batas


In [51]:
#Buat pangkat
kuadrat = []
for i in range(0, 5):
    kuadrat.append(i**2)

In [52]:
kuadrat

[0, 1, 4, 9, 16]

In [62]:
prima = []
for i in range(0, 4):
    prima.append(i**2)

In [63]:
prima

[0, 1, 4, 9]

In [65]:
angka = [i**2 for i in range(0, 5)]
angka

[0, 1, 4, 9, 16]

In [89]:
rentangRendah = 10
rentangTinggi = 50
print('Bilangan kelipatan dua antara', rentangRendah, 'dan', rentangTinggi, ':')
for angka in range(rentangRendah, rentangTinggi):
    if angka > 5:
        print(angka + 5)
    else: 
        print('hasil tidak ditemukan')

Bilangan kelipatan dua antara 10 dan 50 :
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [96]:
#Operasi matematik
#numpy disingkat jadi np
import numpy as np
numpy.version.version

'1.19.4'

In [99]:
#numpy untuk operasi matematik
#Array untuk ngubah list menjadi Vector
vectorA = np.array([1, 2, 3])
vectorA
#bisa untuk operasi matematika
vectorA * 3

array([3, 6, 9])

In [100]:
#hitung penjumlahan dengan numpy
np.sum(vectorA)

6

In [101]:
#hitung mean dengan numpy
np.mean(vectorA)

2.0

In [103]:
#hitung standar deviasi dengan python
np.std(vectorA)
#Standar deviasi adalah nilai statistik yang digunakan untuk menentukan seberapa dekat elemen data-data yang ada dengan nilai rata-rata (mean) dari suatu sampel dan bagaimana data-data tersebar di dalam sampel

0.816496580927726

In [105]:
#bikin random pake numpy
np.random.rand(10)

array([0.3705935 , 0.48890643, 0.08975313, 0.69694067, 0.55135151,
       0.69498939, 0.2870638 , 0.00453092, 0.52282573, 0.6296267 ])

In [108]:
#control randomness
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [3]:
#Fungsi Map
def hitung_kuadrat(n):
    return n*n
bilangan = [1,2,3,4,5]
hasil = map(hitung_kuadrat, bilangan)
#print(hasil)
print(list(hasil))

[1, 4, 9, 16, 25]


In [4]:
def hasil_bagi(n):
    return n%n
bilangan = [25, 20, 15, 10, 7]
hasil = map(hasil_bagi, bilangan)
print(list(hasil))

[0, 0, 0, 0, 0]


In [5]:
def perkalian(n):
    return n * 2
angka = [ 10, 20, 30, 40, 50]
hasil_kali = map(perkalian, angka)
print(list(hasil_kali))

[20, 40, 60, 80, 100]


In [7]:
def perkalian3(n):
    return n * n
angka = [ 10, 20, 30, 40, 50]
hasil_perkalian = map(perkalian3, angka)
print(list(hasil_perkalian))

[100, 400, 900, 1600, 2500]


In [9]:
#fungsi Filter
alfabet = ['a', 'b', 'c', 'd', 'e', 'i', 'k', 'o']
#fungsi penyaring huruf vocal
def filter_vocal(alfabet):
    vocal = ['a', 'e', 'u', 'i', 'o']
    if alfabet in vocal:
        return True
    else:
        return False
vocal_terfilter = filter(filter_vocal, alfabet)
print('Huruf vocal yang tersaring adalah: ')
for vocal in vocal_terfilter:
    print(vocal)

Huruf vocal yang tersaring adalah: 
a
e
i
o


In [10]:
data_awal= ['a', 'b', 'c', 'd', 'e', 'f', 'h', 'j', 'i']
#bikin fungsi penyaring huruf
def filter_huruf(alfabet):
    vocal = ['a', 'e', 'u', 'o', 'i']
    if alfabet in vocal:
        return True
    else:
        return False
vocal_terfilter = filter(filter_huruf, alfabet)
print('Huruf alfabet yng ada di data adalah: ')
for vocal in vocal_terfilter:
    print(vocal)

Huruf alfabet yng ada di data adalah: 
a
e
i
o
